"""add new column

Revision ID: 04b415e851ec
Revises: 013
Create Date: 2026-07-09 18:16:30.176481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04b415e851ec'
down_revision: Union[str, None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoho_oauth_tokens')
    op.drop_table('sync_metadata')
    op.drop_index(op.f('ix_zoho_applications_zoho_candidate_id'), table_name='zoho_applications')
    op.drop_index(op.f('ix_zoho_applications_zoho_job_opening_id'), table_name='zoho_applications')
    op.drop_table('zoho_applications')
    op.drop_index(op.f('ix_zoho_job_openings_mapped_job_id'), table_name='zoho_job_openings')
    op.drop_table('zoho_job_openings')
    op.drop_index(op.f('ix_zoho_candidates_email'), table_name='zoho_candidates')
    op.drop_table('zoho_candidates')
    op.drop_index(op.f('ix_job_candidate_pools_job'), table_name='job_candidate_pools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_candidate_pools_job'), 'job_candidate_pools', ['job_id'], unique=False)
    op.create_table('zoho_applications',
    sa.Column('zoho_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zoho_candidate_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zoho_job_opening_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('application_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['zoho_candidate_id'], ['zoho_candidates.zoho_id'], name=op.f('zoho_applications_zoho_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['zoho_job_opening_id'], ['zoho_job_openings.zoho_id'], name=op.f('zoho_applications_zoho_job_opening_id_fkey')),
    sa.PrimaryKeyConstraint('zoho_id', name=op.f('zoho_applications_pkey'))
    )
    op.create_index(op.f('ix_zoho_applications_zoho_job_opening_id'), 'zoho_applications', ['zoho_job_opening_id'], unique=False)
    op.create_index(op.f('ix_zoho_applications_zoho_candidate_id'), 'zoho_applications', ['zoho_candidate_id'], unique=False)
    op.create_table('zoho_candidates',
    sa.Column('zoho_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_profile_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resume_downloaded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('resume_attachment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('local_candidate_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['local_candidate_email'], ['candidates.email'], name=op.f('zoho_candidates_local_candidate_email_fkey')),
    sa.PrimaryKeyConstraint('zoho_id', name=op.f('zoho_candidates_pkey'))
    )
    op.create_index(op.f('ix_zoho_candidates_email'), 'zoho_candidates', ['email'], unique=False)
    op.create_table('sync_metadata',
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_modified_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'idle'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('records_synced', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('entity_type', name=op.f('sync_metadata_pkey'))
    )
    op.create_table('zoho_job_openings',
    sa.Column('zoho_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posting_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mapped_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mapped_job_id'], ['jobs.id'], name=op.f('zoho_job_openings_mapped_job_id_fkey')),
    sa.PrimaryKeyConstraint('zoho_id', name=op.f('zoho_job_openings_pkey'))
    )
    op.create_index(op.f('ix_zoho_job_openings_mapped_job_id'), 'zoho_job_openings', ['mapped_job_id'], unique=False)
    op.create_table('zoho_oauth_tokens',
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('service_name', name=op.f('zoho_oauth_tokens_pkey'))
    )
    # ### end Alembic commands ###
