"""Add performance indexes for candidates

Revision ID: 2675b80e7dd3
Revises: e4483e971205
Create Date: 2026-07-21 13:21:18.745277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2675b80e7dd3'
down_revision: Union[str, None] = 'e4483e971205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_source_name'), 'candidates', ['source_name'], unique=False)
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_candidate_pools_candidate_id'), 'job_candidate_pools', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_candidate_pools_job_id'), 'job_candidate_pools', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_candidate_pools_pool_status'), 'job_candidate_pools', ['pool_status'], unique=False)
    op.create_index(op.f('ix_processing_logs_entity_id'), 'processing_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_processing_logs_entity_type'), 'processing_logs', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_logs_entity_type'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_entity_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_job_candidate_pools_pool_status'), table_name='job_candidate_pools')
    op.drop_index(op.f('ix_job_candidate_pools_job_id'), table_name='job_candidate_pools')
    op.drop_index(op.f('ix_job_candidate_pools_candidate_id'), table_name='job_candidate_pools')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_index(op.f('ix_candidates_source_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    # ### end Alembic commands ###
