"""Add zoho fields to jobs

Revision ID: 38dd6d201d17
Revises: 011
Create Date: 2026-07-13 16:42:14.422403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd6d201d17'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('cv_pdf', sa.LargeBinary(), nullable=True))
    op.drop_index(op.f('ix_job_candidate_pools_job'), table_name='job_candidate_pools')
    op.add_column('jobs', sa.Column('zoho_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('zoho_data', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['zoho_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'zoho_data')
    op.drop_column('jobs', 'zoho_id')
    op.create_index(op.f('ix_job_candidate_pools_job'), 'job_candidate_pools', ['job_id'], unique=False)
    op.drop_column('candidates', 'cv_pdf')
    # ### end Alembic commands ###
