"""Add salary to jobs

Revision ID: a61c3907aaad
Revises: 38dd6d201d17
Create Date: 2026-07-13 17:40:27.604394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61c3907aaad'
down_revision: Union[str, None] = '38dd6d201d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'salary')
    # ### end Alembic commands ###
