"""Add Zoho Forms integration fields

Revision ID: de02456ba8cf
Revises: 04b415e851ec
Create Date: 2026-07-09 18:24:50.994036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de02456ba8cf'
down_revision: Union[str, None] = '04b415e851ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_imports', sa.Column('zoho_submission_id', sa.String(), nullable=True))
    op.add_column('candidate_imports', sa.Column('zoho_form_id', sa.String(), nullable=True))
    op.add_column('candidate_imports', sa.Column('zoho_data', sa.JSON(), nullable=True))
    op.add_column('candidate_imports', sa.Column('merge_strategy', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('zoho_submission_id', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('zoho_form_id', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('data_sources', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('last_zoho_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'last_zoho_sync')
    op.drop_column('candidates', 'data_sources')
    op.drop_column('candidates', 'zoho_form_id')
    op.drop_column('candidates', 'zoho_submission_id')
    op.drop_column('candidate_imports', 'merge_strategy')
    op.drop_column('candidate_imports', 'zoho_data')
    op.drop_column('candidate_imports', 'zoho_form_id')
    op.drop_column('candidate_imports', 'zoho_submission_id')
    # ### end Alembic commands ###
