"""Add import_metadata to CandidateImport

Revision ID: f82f077c819e
Revises: 5b669e71b8d8
Create Date: 2026-07-18 02:02:39.937026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82f077c819e'
down_revision: Union[str, None] = '5b669e71b8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_imports', sa.Column('import_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_imports', 'import_metadata')
    # ### end Alembic commands ###
